#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <device> <dataset> <database> <dir>"
    exit 1
fi

# Assign command-line arguments to variables
export CUDA_VISIBLE_DEVICES="$1"
export DATASET_NAME="$2"
export DATABASE_NAME="$3"
export DIR="$4"

# Definite the parameters
# Set environment variables
export DATASETS_DIR=/data/xxx/datasets
export DATASET="${DATASET_NAME}:${DATABASE_NAME}"
export MODEL=/data/xxx/models/gpt-4o-mini
export ASSIST_MODEL=/data/xxx/models/Meta-Llama-3.1-8B-Instruct
export EMBED_MODEL=/data/xxx/models/xlm-roberta-large

# Generate YAML file path based on the provided directory and dataset name
yaml_file="${DIR}/${DATASET_NAME}.yaml"

# save directory settings
export RESULT_DIR_PREFIX=results_opt_gpt4/icl_llama31

export PROCESS_DATABASE_TEXT=""
export PROCESS_KEY=""
export PROMPT_ASSIST=detailed_explanation_prompt
export PROMPT_PROBING=detailed_detection_prompt
export PROMPT_EXPLANATION=standard_explanation
export PROMPT_ICL=min_edit_fewshot

export EXAMPLE_MODE_ERROR=relation
export EXAMPLE_MODE_CORRECT=text
export EXAMPLE_NUM_ERROR_RETRIEVAL=4
export EXAMPLE_NUM_CORRECT_RETRIEVAL=4
export EXAMPLE_NUM_ERROR=4
export EXAMPLE_NUM_CORRECT=4
export EXAMPLE_RETRIEVAL_DEFAULT=single_key
export EXAMPLE_RETRIEVAL_PROBING=single_key

export DIR_PREPARE=${RESULT_DIR_PREFIX}_prepare
export DIR_PROBING=${RESULT_DIR_PREFIX}_probing
export DIR_RETRIEVE_BY_PROBING=${RESULT_DIR_PREFIX}_retrieve_by_probing

export DIR_EXPLANATION_FROM_RANDOM_ICL=${RESULT_DIR_PREFIX}_explanation_from_random
export DIR_RETRIEVE_BY_EXPLANATION_FROM_RANDOM_ICL=${RESULT_DIR_PREFIX}_retrieve_by_explanation_from_random


export DIR_RETRIEVE_BY_BM25=${RESULT_DIR_PREFIX}_retrieve_by_bm25
export DIR_RETRIEVE_BY_SEMANTIC=${RESULT_DIR_PREFIX}_retrieve_by_semantic

export DIR_EXPLANATION_FROM_SEMANTIC_ICL=${RESULT_DIR_PREFIX}_explanation_from_semantic
export DIR_RETRIEVE_BY_EXPLANATION_FROM_SEMANTIC_ICL=${RESULT_DIR_PREFIX}_retrieve_by_explanation_from_semantic

export RESULT_DIR_ICL_RANDOM=${RESULT_DIR_PREFIX}_res_random
export RESULT_DIR_ICL_BM25=${RESULT_DIR_PREFIX}_res_bm25
export RESULT_DIR_ICL_SEMANTIC=${RESULT_DIR_PREFIX}_res_semantic
export RESULT_DIR_ICL_PROBING=${RESULT_DIR_PREFIX}_res_probing
export RESULT_DIR_ICL_PROBING_W_DESC=${RESULT_DIR_PREFIX}_res_probing_with_description
export RESULT_DIR_REFINEMENT_ICL_FROM_RANDOM=${RESULT_DIR_PREFIX}_res_refinement_random
export RESULT_DIR_REFINEMENT_ICL_FROM_SEMANTIC=${RESULT_DIR_PREFIX}_res_refinement_semantic


# check settings
bash scripts/pipeline/show_settings.sh \
  CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" \
  DATASET_NAME="$DATASET_NAME" \
  DATABASE_NAME="$DATABASE_NAME" \
  DATASETS_DIR="$DATASETS_DIR" \
  DATASET="$DATASET" \
  MODEL="$MODEL" \
  ASSIST_MODEL="$ASSIST_MODEL" \
  EMBED_MODEL="$EMBED_MODEL" \
  RESULT_DIR_PREFIX="$RESULT_DIR_PREFIX" \
  PROCESS_DATABASE_TEXT="$PROCESS_DATABASE_TEXT" \
  PROCESS_KEY="$PROCESS_KEY" \
  PROMPT_ASSIST="$PROMPT_ASSIST" \
  PROMPT_PROBING="$PROMPT_PROBING" \
  PROMPT_EXPLANATION="$PROMPT_EXPLANATION" \
  PROMPT_ICL="$PROMPT_ICL" \
  EXAMPLE_MODE_ERROR="$EXAMPLE_MODE_ERROR" \
  EXAMPLE_MODE_CORRECT="$EXAMPLE_MODE_CORRECT" \
  EXAMPLE_NUM_ERROR_RETRIEVAL="$EXAMPLE_NUM_ERROR_RETRIEVAL" \
  EXAMPLE_NUM_CORRECT_RETRIEVAL="$EXAMPLE_NUM_CORRECT_RETRIEVAL" \
  EXAMPLE_NUM_ERROR="$EXAMPLE_NUM_ERROR" \
  EXAMPLE_NUM_CORRECT="$EXAMPLE_NUM_CORRECT" \
  EXAMPLE_RETRIEVAL_DEFAULT="$EXAMPLE_RETRIEVAL_DEFAULT" \
  EXAMPLE_RETRIEVAL_PROBING="$EXAMPLE_RETRIEVAL_PROBING" \
  DIR_PREPARE="$DIR_PREPARE" \
  DIR_PROBING="$DIR_PROBING" \
  DIR_RETRIEVE_BY_PROBING="$DIR_RETRIEVE_BY_PROBING" \
  DIR_EXPLANATION_FROM_RANDOM_ICL="$DIR_EXPLANATION_FROM_RANDOM_ICL" \
  DIR_RETRIEVE_BY_EXPLANATION_FROM_RANDOM_ICL="$DIR_RETRIEVE_BY_EXPLANATION_FROM_RANDOM_ICL" \
  DIR_RETRIEVE_BY_BM25="$DIR_RETRIEVE_BY_BM25" \
  DIR_RETRIEVE_BY_SEMANTIC="$DIR_RETRIEVE_BY_SEMANTIC" \
  DIR_EXPLANATION_FROM_SEMANTIC_ICL="$DIR_EXPLANATION_FROM_SEMANTIC_ICL" \
  DIR_RETRIEVE_BY_EXPLANATION_FROM_SEMANTIC_ICL="$DIR_RETRIEVE_BY_EXPLANATION_FROM_SEMANTIC_ICL" \
  RESULT_DIR_ICL_RANDOM="$RESULT_DIR_ICL_RANDOM" \
  RESULT_DIR_ICL_BM25="$RESULT_DIR_ICL_BM25" \
  RESULT_DIR_ICL_SEMANTIC="$RESULT_DIR_ICL_SEMANTIC" \
  RESULT_DIR_ICL_PROBING="$RESULT_DIR_ICL_PROBING" \
  RESULT_DIR_ICL_PROBING_W_DESC="$RESULT_DIR_ICL_PROBING_W_DESC" \
  RESULT_DIR_REFINEMENT_ICL_FROM_RANDOM="$RESULT_DIR_REFINEMENT_ICL_FROM_RANDOM" \
  RESULT_DIR_REFINEMENT_ICL_FROM_SEMANTIC="$RESULT_DIR_REFINEMENT_ICL_FROM_SEMANTIC"

# save yaml
# check settings
python yaml_save.py \
  CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" \
  DATASET_NAME="$DATASET_NAME" \
  DATABASE_NAME="$DATABASE_NAME" \
  DATASETS_DIR="$DATASETS_DIR" \
  DATASET="$DATASET" \
  MODEL="$MODEL" \
  ASSIST_MODEL="$ASSIST_MODEL" \
  EMBED_MODEL="$EMBED_MODEL" \
  RESULT_DIR_PREFIX="$RESULT_DIR_PREFIX" \
  PROCESS_DATABASE_TEXT="$PROCESS_DATABASE_TEXT" \
  PROCESS_KEY="$PROCESS_KEY" \
  PROMPT_ASSIST="$PROMPT_ASSIST" \
  PROMPT_PROBING="$PROMPT_PROBING" \
  PROMPT_EXPLANATION="$PROMPT_EXPLANATION" \
  PROMPT_ICL="$PROMPT_ICL" \
  EXAMPLE_MODE_ERROR="$EXAMPLE_MODE_ERROR" \
  EXAMPLE_MODE_CORRECT="$EXAMPLE_MODE_CORRECT" \
  EXAMPLE_NUM_ERROR_RETRIEVAL="$EXAMPLE_NUM_ERROR_RETRIEVAL" \
  EXAMPLE_NUM_CORRECT_RETRIEVAL="$EXAMPLE_NUM_CORRECT_RETRIEVAL" \
  EXAMPLE_NUM_ERROR="$EXAMPLE_NUM_ERROR" \
  EXAMPLE_NUM_CORRECT="$EXAMPLE_NUM_CORRECT" \
  EXAMPLE_RETRIEVAL_DEFAULT="$EXAMPLE_RETRIEVAL_DEFAULT" \
  EXAMPLE_RETRIEVAL_PROBING="$EXAMPLE_RETRIEVAL_PROBING" \
  DIR_PREPARE="$DIR_PREPARE" \
  DIR_PROBING="$DIR_PROBING" \
  DIR_RETRIEVE_BY_PROBING="$DIR_RETRIEVE_BY_PROBING" \
  DIR_EXPLANATION_FROM_RANDOM_ICL="$DIR_EXPLANATION_FROM_RANDOM_ICL" \
  DIR_RETRIEVE_BY_EXPLANATION_FROM_RANDOM_ICL="$DIR_RETRIEVE_BY_EXPLANATION_FROM_RANDOM_ICL" \
  DIR_RETRIEVE_BY_BM25="$DIR_RETRIEVE_BY_BM25" \
  DIR_RETRIEVE_BY_SEMANTIC="$DIR_RETRIEVE_BY_SEMANTIC" \
  DIR_EXPLANATION_FROM_SEMANTIC_ICL="$DIR_EXPLANATION_FROM_SEMANTIC_ICL" \
  DIR_RETRIEVE_BY_EXPLANATION_FROM_SEMANTIC_ICL="$DIR_RETRIEVE_BY_EXPLANATION_FROM_SEMANTIC_ICL" \
  RESULT_DIR_ICL_RANDOM="$RESULT_DIR_ICL_RANDOM" \
  RESULT_DIR_ICL_BM25="$RESULT_DIR_ICL_BM25" \
  RESULT_DIR_ICL_SEMANTIC="$RESULT_DIR_ICL_SEMANTIC" \
  RESULT_DIR_ICL_PROBING="$RESULT_DIR_ICL_PROBING" \
  RESULT_DIR_ICL_PROBING_W_DESC="$RESULT_DIR_ICL_PROBING_W_DESC" \
  RESULT_DIR_REFINEMENT_ICL_FROM_RANDOM="$RESULT_DIR_REFINEMENT_ICL_FROM_RANDOM" \
  RESULT_DIR_REFINEMENT_ICL_FROM_SEMANTIC="$RESULT_DIR_REFINEMENT_ICL_FROM_SEMANTIC" \
  --yaml $yaml_file

